name: ci rails
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: app_ci
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Start MySql
        run: |
          sudo service mysql start

      - name: Setup database and run tests
        env:
          RAILS_ENV: test
          DB_PORT: 3306
          DB_NAME: app_ci
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails db:migrate
          bin/rails test
